name: Cloudflare

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Cloudflare Pages GitHub Action
        uses: cloudflare/pages-action@v1.1.0
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: furst
          directory: /assets
          gitHubToken: ${{ secrets.GH_TOKEN }}
